/*
1. Display all films longer than 120 minutes, sorted by duration.
This query returns the titles and durations of films with a running time greater than 120 minutes. 
The results are sorted in ascending order by film length.
*/
SELECT 
	title AS film_title, 
	length
FROM film 
WHERE length > 120 ORDER BY length ASC;

/*
2. Display a list of customers from a specific city.
This query returns the first name, last name, and city of customers who live in York.
The city York is used as an example and can be replaced with any other city by modifying the WHERE clause.
The query joins the customer, address, and city tables to retrieve the required information.
*/
SELECT 
	ctmr.first_name, 
	ctmr.last_name, 
	ct.city
FROM customer ctmr
JOIN address adrs ON ctmr.address_id = adrs.address_id
JOIN city ct ON adrs.city_id =  ct.city_id
WHERE ct.city = 'York';
 
/*
3. Find all films whose titles contain a specific word.
This query returns the titles of films containing the word "LIFE" anywhere in the title.
The LIKE operator together with the % wildcard allows matching the keyword regardless of its position in the string.
The keyword "LIFE" is used as an example and can be replaced with any other search term.
*/
SELECT 
	title AS film_title,
FROM film
WHERE title LIKE '%LIFE%';
 
/*
4. Count the total number of films in each category.
This query calculates the number of films in each category.
The result is obtained by joining the film, film_category, and category tables. 
Since there is no direct relationship between film and category, the intermediate film_category table is used.
*/
SELECT 
	ctg.name AS category_name,
	COUNT(*) FROM film
JOIN film_category f_c ON film.film_id = f_c.film_id
JOIN category  ctg ON f_c.category_id = ctg.category_id 
GROUP BY ctg.name;


/*
5. Calculate the total payment amount for each customer and display the top 10 customers.
This query calculates the total payment amount made by each customer.
The results are sorted in descending order, and only the top 10 customers with the highest payment totals are returned.
*/ 
SELECT 
	ctmr.first_name,
	ctmr.last_name,
	SUM(amount) payment_sum
FROM customer ctmr
JOIN payment ON ctmr.customer_id = payment.customer_id
GROUP BY ctmr.customer_id
ORDER BY SUM(amount) DESC
LIMIT 10;

/*
6. Calculate the average rental duration (in days).
This query calculates the average rental duration using the rental_duration column from the film table.
The result is rounded to one decimal place for better readability.
*/ 
SELECT 
ROUND(AVG(rental_duration),1) avg_rental_by_days
FROM film ;
 
/*
7. Display categories containing more than a specified number of films.
This query counts the number of films in each category and returns only those categories containing more than 65 films.
The threshold value can easily be changed in the HAVING clause.
*/
SELECT 
	ctgr.name category_name,,
	COUNT(f.film_id) count_films
FROM category ctgr
JOIN film_category f_c ON f_c.category_id = ctgr.category_id
JOIN film f ON f_c.film_id = f.film_id
GROUP BY ctgr.name
HAVING COUNT(f.film_id) > 65;

/*
8. Display all films together with their categories.
This query returns film titles along with their corresponding categories.
The information is obtained by joining the film, film_category, and category tables.
*/
SELECT 
	f.title film_title,
	ctgr.name
FROM film f
JOIN film_category f_c ON f_c.film_id = f.film_id
JOIN category ctgr ON f_c.category_id = ctgr.category_id; 
 
/*
9. Display all films rented by a specific customer with rental dates.
This query returns the films rented by the customer named Bob, along with the corresponding rental dates.
The name Bob is used for demonstration purposes. In real-world applications, 
it is recommended to filter by the unique customer_id instead of the customer's name.
*/
SELECT 
	c.first_name,
	c.last_name,
	f.title film_title,
	r.rental_date
FROM customer c
JOIN rental r ON c.customer_id = r.customer_id
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN film f ON i.film_id = f.film_id
WHERE c.first_name = 'BOB';

/*
10. Calculate total revenue for each store.
This query calculates the total revenue generated by each store by summing all payment amounts.
The result is obtained by joining the store, staff, and payment tables.
*/ 
SELECT 
	s.store_id,
	SUM(p.amount) total_revenue
FROM store s 
JOIN staff st ON s.store_id = st.store_id
JOIN payment p ON st.staff_id = p.staff_id
GROUP BY s.store_id;
 

/*
11. Display the top 10 actors by number of films.
This query counts the number of films each actor has appeared in.
The results are sorted in descending order, and only the top 10 actors are returned.
*/
SELECT 
	a.actor_id,
	a.first_name,
	a.last_name,
	COUNT(f_a.film_id) AS film_count
FROM actor a
JOIN film_actor f_a ON a.actor_id = f_a.actor_id
GROUP BY a.actor_id, a.first_name, a.last_name
ORDER BY film_count DESC
LIMIT 10;
 
/*
12. Display each customer's payments with a running total.
This query displays every customer payment together with a cumulative payment total.
It uses the SUM() OVER() window function, partitioned by customer and ordered chronologically by payment date.
*/
SELECT 
	customer_id,
	payment_date,
	amount,
	SUM(amount) OVER (PARTITION BY customer_id ORDER BY payment_date) running_total
FROM payment;
 
/*
13. Rank films by duration within each category.
This query ranks films by duration inside each category using the DENSE_RANK() window function.
Films with the same duration receive the same rank, and no ranking gaps are created.
The ranking is performed separately for each category and ordered by film duration in descending order.
*/
SELECT 
	c.name category_name,
	f.title film_title,
	DENSE_RANK() OVER(PARTITION BY c.name ORDER BY f.length DESC) rank_by_length
FROM film f
JOIN film_category f_c ON f.film_id = f_c.film_id
JOIN category c ON f_c.category_id = c.category_id;
 
/*
14. Display monthly revenue and the change compared to the previous month.
This query calculates monthly revenue and uses the LAG() window function to retrieve the previous month's revenue.
It then calculates the revenue change compared with the previous month.
*/
SELECT 
    DATE_TRUNC('month', payment_date) AS month,
	LAG(SUM(amount)) OVER (ORDER BY DATE_TRUNC('month', payment_date)) AS prev_revenue,
    SUM(amount) AS revenue,
    SUM(amount) - LAG(SUM(amount)) OVER (ORDER BY DATE_TRUNC('month', payment_date)) AS change
FROM payment
GROUP BY month
ORDER BY month;
 


